[package]
name = "life_struggle"
version = "0.1.0"
authors = ["Craig Macomber <CraigM@CraigM.info>"]

[dependencies]
num-integer = "0.1"
rayon = "0.9"
time = "*"
fixedbitset = "0.1"
image = "*"
rand = "0.4"

[profile.release]
# lto = true

[profile.test]
opt-level = 2